-- COMPLETE CLOTHING STORE SCHEMA (V8)
-- Includes: Products, Categories, Orders, Users, Reviews, Coupons, Blog, Banners, Settings
-- Includes: Triggers for User Profile creation
-- Includes: RLS Policies for Admin/Customer security

-- 1. ENABLE RLS (Row Level Security) on all tables by default
-- Run this just in case
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO service_role;

-- 2. CREATE TABLES

-- PROFILES (Links to auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT UNIQUE,
  full_name TEXT,
  role TEXT DEFAULT 'customer' CHECK (role IN ('admin', 'customer')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- CATEGORIES
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE,
  image_url TEXT,
  parent_id BIGINT REFERENCES public.categories(id),
  item_count INT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- PRODUCTS
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE,
  price NUMERIC NOT NULL,
  original_price NUMERIC,
  category TEXT,
  brand TEXT,
  unit TEXT,
  sku TEXT,
  images TEXT[], -- Array of image URLs
  image_url TEXT, -- Fallback main image
  short_description TEXT,
  description TEXT,
  badge TEXT,
  is_featured BOOLEAN DEFAULT false,
  variants JSONB DEFAULT '[]'::jsonb, -- JSON Array of variants
  attributes JSONB DEFAULT '[]'::jsonb, -- JSON Array of attributes
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- ORDERS
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_email TEXT,
  customer_phone TEXT,
  customer_address TEXT,
  customer_district TEXT,
  customer_area TEXT,
  subtotal NUMERIC DEFAULT 0,
  shipping_cost NUMERIC DEFAULT 0,
  discount NUMERIC DEFAULT 0,
  total NUMERIC DEFAULT 0,
  status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Processing', 'Delivered', 'Cancelled')),
  items JSONB DEFAULT '[]'::jsonb, -- Snapshot of cart items at purchase
  coupon_code TEXT,
  user_id UUID REFERENCES auth.users(id),
  date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- SETTINGS (Key-Value Store for Store Info, Shipping Fees, Home Sections)
CREATE TABLE IF NOT EXISTS public.settings (
  key TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- WISHLIST
CREATE TABLE IF NOT EXISTS public.wishlist (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(user_id, product_id)
);
ALTER TABLE public.wishlist ENABLE ROW LEVEL SECURITY;

-- ADDRESSES
CREATE TABLE IF NOT EXISTS public.addresses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT,
  phone TEXT,
  address_line TEXT,
  district TEXT,
  area TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.addresses ENABLE ROW LEVEL SECURITY;

-- BRANDS
CREATE TABLE IF NOT EXISTS public.brands (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE,
  logo_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.brands ENABLE ROW LEVEL SECURITY;

-- ATTRIBUTES (Size, Color, etc.)
CREATE TABLE IF NOT EXISTS public.attributes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  values JSONB DEFAULT '[]'::jsonb, -- Array of {id, value}
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.attributes ENABLE ROW LEVEL SECURITY;

-- COUPONS
CREATE TABLE IF NOT EXISTS public.coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  discount_type TEXT NOT NULL CHECK (discount_type IN ('Fixed', 'Percentage')),
  discount_value NUMERIC NOT NULL,
  minimum_spend NUMERIC DEFAULT 0,
  expiry_date DATE NOT NULL,
  status TEXT DEFAULT 'Active' CHECK (status IN ('Active', 'Inactive')),
  auto_apply BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

-- REVIEWS
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
  product_name TEXT,
  author_name TEXT,
  rating INT CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  reply TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- PAGES (Static Pages like About, Contact)
CREATE TABLE IF NOT EXISTS public.pages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  content TEXT,
  is_published BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.pages ENABLE ROW LEVEL SECURITY;

-- BANNERS
CREATE TABLE IF NOT EXISTS public.banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  image_url TEXT NOT NULL,
  title TEXT,
  subtitle TEXT,
  link TEXT,
  sort_order INT DEFAULT 0,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.banners ENABLE ROW LEVEL SECURITY;

-- BLOG POSTS
CREATE TABLE IF NOT EXISTS public.blog_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  excerpt TEXT,
  content TEXT,
  author TEXT,
  image_url TEXT,
  slug TEXT UNIQUE,
  tags TEXT[],
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
ALTER TABLE public.blog_posts ENABLE ROW LEVEL SECURITY;


-- 3. STORAGE SETUP
-- Creates the 'product-images' bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public) 
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'product-images' );

DROP POLICY IF EXISTS "Auth Upload" ON storage.objects;
CREATE POLICY "Auth Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'product-images' AND auth.role() = 'authenticated' );


-- 4. FUNCTIONS & TRIGGERS

-- Function to get the current user's role from public.profiles
CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS text AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid();
$$ LANGUAGE sql SECURITY DEFINER SET search_path = public;

-- Trigger to create profile validation
-- NOTE: REPLACE 'msmraqeeb@gmail.com' WITH YOUR ACTUAL ADMIN EMAIL if different
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    -- EXAMPLE: Auto-approve admins based on domain or specific list
    CASE 
      WHEN NEW.email LIKE '%@clothingstore.com' THEN 'admin' -- Auto-admin for domain
      WHEN NEW.email IN ('msmraqeeb@gmail.com', 'admin@example.com') THEN 'admin' -- Specific allowlist
      ELSE 'customer' 
    END
  )
  ON CONFLICT (id) DO UPDATE SET role = EXCLUDED.role;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();


-- 5. RLS POLICIES (SECURITY)

-- Clean up old policies first to avoid duplicates
DO $$ 
DECLARE 
  pol RECORD;
BEGIN
  FOR pol IN (SELECT policyname, tablename FROM pg_policies WHERE schemaname = 'public') LOOP
    EXECUTE 'DROP POLICY IF EXISTS "' || pol.policyname || '" ON public.' || pol.tablename;
  END LOOP;
END $$;

-- --- PROFILES ---
CREATE POLICY "Admins view all profiles" ON public.profiles FOR SELECT USING ( public.get_my_role() = 'admin' );
CREATE POLICY "Users manage own profile" ON public.profiles FOR ALL USING (auth.uid() = id);

-- --- PRODUCTS ---
CREATE POLICY "Admins manage products" ON public.products FOR ALL TO authenticated
USING ( public.get_my_role() = 'admin' );
CREATE POLICY "Public read products" ON public.products FOR SELECT USING (true);

-- --- CATEGORIES ---
CREATE POLICY "Admins manage categories" ON public.categories FOR ALL TO authenticated
USING ( public.get_my_role() = 'admin' );
CREATE POLICY "Public read categories" ON public.categories FOR SELECT USING (true);

-- --- ORDERS ---
CREATE POLICY "Admins manage orders" ON public.orders FOR ALL TO authenticated
USING ( public.get_my_role() = 'admin' );
CREATE POLICY "Users manage own orders" ON public.orders FOR ALL USING ( auth.uid() = user_id );
CREATE POLICY "Anyone can insert orders" ON public.orders FOR INSERT WITH CHECK (true);

-- --- SETTINGS ---
CREATE POLICY "Admins manage settings" ON public.settings FOR ALL TO authenticated
USING ( public.get_my_role() = 'admin' );
CREATE POLICY "Public read settings" ON public.settings FOR SELECT USING (true);

-- --- BRANDS ---
CREATE POLICY "Admins manage brands" ON public.brands FOR ALL TO authenticated
USING ( public.get_my_role() = 'admin' );
CREATE POLICY "Public read brands" ON public.brands FOR SELECT USING (true);

-- --- ATTRIBUTES ---
CREATE POLICY "Admins manage attributes" ON public.attributes FOR ALL TO authenticated
USING ( public.get_my_role() = 'admin' );
CREATE POLICY "Public read attributes" ON public.attributes FOR SELECT USING (true);

-- --- COUPONS ---
CREATE POLICY "Admins manage coupons" ON public.coupons FOR ALL TO authenticated
USING ( public.get_my_role() = 'admin' );
CREATE POLICY "Public read coupons" ON public.coupons FOR SELECT USING (true);

-- --- REVIEWS ---
CREATE POLICY "Admins manage reviews" ON public.reviews FOR ALL TO authenticated
USING ( public.get_my_role() = 'admin' );
CREATE POLICY "Public read reviews" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Users insert reviews" ON public.reviews FOR INSERT TO authenticated WITH CHECK (true);

-- --- PAGES ---
CREATE POLICY "Admins manage pages" ON public.pages FOR ALL TO authenticated
USING ( public.get_my_role() = 'admin' );
CREATE POLICY "Public read pages" ON public.pages FOR SELECT USING (is_published = true);

-- --- BANNERS ---
CREATE POLICY "Admins manage banners" ON public.banners FOR ALL TO authenticated
USING ( public.get_my_role() = 'admin' );
CREATE POLICY "Public read banners" ON public.banners FOR SELECT USING (true);

-- --- BLOG POSTS ---
CREATE POLICY "Admins manage blog" ON public.blog_posts FOR ALL TO authenticated
USING ( public.get_my_role() = 'admin' );
CREATE POLICY "Public read blog" ON public.blog_posts FOR SELECT USING (true);

-- --- WISHLIST ---
CREATE POLICY "Users manage own wishlist" ON public.wishlist FOR ALL USING (auth.uid() = user_id);

-- --- ADDRESSES ---
CREATE POLICY "Users manage own addresses" ON public.addresses FOR ALL USING (auth.uid() = user_id);
